---
- name: Deploy Uptime Kuma Container Stack
  hosts: all
  gather_facts: false

  vars_files:
    - config.yml

  tasks:
    - name: Deploy NGINX reverse proxy
      ansible.builtin.include_role:
        name: nginx
        rolespec_validate: false

    - name: Deploy Uptime Kuma
      ansible.builtin.include_role:
        name: uptimekuma
