---
- name: Restart Uptime Kuma Docker Compose deployment
  ansible.builtin.command:
    cmd: docker compose --ansi never --progress plain restart
    chdir: "{{ uptimekuma_docker_path }}"
  changed_when: true
  listen: restart uptimekuma
